// <auto-generated />
using System;
using Hoteldotnetserver.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelServer.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20260601080621_Initcreate")]
    partial class Initcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hoteldotnetserver.Entities.Amenities", b =>
                {
                    b.Property<Guid>("_amenityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("_amenityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_amenityId");

                    b.ToTable("Amenities");
                });

            modelBuilder.Entity("Hoteldotnetserver.Entities.Bookings", b =>
                {
                    b.Property<Guid>("_bookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("_bookingStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("_cancelAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("_checkInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("_checkOutDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("_createAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("_num_Guests")
                        .HasColumnType("int");

                    b.Property<Guid>("_propertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("_totalPrice")
                        .HasColumnType("int");

                    b.Property<Guid>("_userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("_bookingId");

                    b.HasIndex("_propertyId");

                    b.HasIndex("_userId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Hoteldotnetserver.Entities.Payments", b =>
                {
                    b.Property<Guid>("_paymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("_bookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("_paymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("_paymentStatus")
                        .HasColumnType("int");

                    b.Property<string>("_paymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("_totalAmount")
                        .HasColumnType("int");

                    b.HasKey("_paymentId");

                    b.HasIndex("_bookingId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Hoteldotnetserver.Entities.Properties", b =>
                {
                    b.Property<Guid>("_propertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("_propertyDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_propertyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("_propertyOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("maxGuests")
                        .HasColumnType("int");

                    b.Property<string>("propertyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("value_perNight")
                        .HasColumnType("int");

                    b.HasKey("_propertyId");

                    b.HasIndex("_propertyOwnerId");

                    b.ToTable("properties");
                });

            modelBuilder.Entity("Hoteldotnetserver.Entities.PropertyAmenities", b =>
                {
                    b.Property<Guid>("_propertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("_amenityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("_propertyId", "_amenityId");

                    b.HasIndex("_amenityId");

                    b.ToTable("PropertyAmenities");
                });

            modelBuilder.Entity("Hoteldotnetserver.Entities.PropertyImages", b =>
                {
                    b.Property<Guid>("_imageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("_imageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("_isPrimary")
                        .HasColumnType("bit");

                    b.Property<Guid>("_propertyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("_imageId");

                    b.HasIndex("_propertyId");

                    b.ToTable("propertyImages");
                });

            modelBuilder.Entity("Hoteldotnetserver.Entities.Reviews", b =>
                {
                    b.Property<Guid>("_reviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("_comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("_createdAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("_propertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("_rating")
                        .HasColumnType("int");

                    b.Property<Guid>("_userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("_reviewId");

                    b.HasIndex("_propertyId");

                    b.HasIndex("_userId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Hoteldotnetserver.Entities.Users", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("bit");

                    b.Property<bool>("Permissions")
                        .HasColumnType("bit");

                    b.Property<DateTime>("createdDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("emailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("updatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Hoteldotnetserver.Entities.Bookings", b =>
                {
                    b.HasOne("Hoteldotnetserver.Entities.Properties", "Property")
                        .WithMany("Bookings")
                        .HasForeignKey("_propertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hoteldotnetserver.Entities.Users", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("_userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hoteldotnetserver.Entities.Payments", b =>
                {
                    b.HasOne("Hoteldotnetserver.Entities.Bookings", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("_bookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Hoteldotnetserver.Entities.Properties", b =>
                {
                    b.HasOne("Hoteldotnetserver.Entities.Users", "User")
                        .WithMany("Properties")
                        .HasForeignKey("_propertyOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hoteldotnetserver.Entities.PropertyAmenities", b =>
                {
                    b.HasOne("Hoteldotnetserver.Entities.Amenities", "Amenity")
                        .WithMany("PropertyAmenities")
                        .HasForeignKey("_amenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hoteldotnetserver.Entities.Properties", "Property")
                        .WithMany("PropertyAmenities")
                        .HasForeignKey("_propertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Hoteldotnetserver.Entities.PropertyImages", b =>
                {
                    b.HasOne("Hoteldotnetserver.Entities.Properties", "Property")
                        .WithMany("PropertyImages")
                        .HasForeignKey("_propertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Hoteldotnetserver.Entities.Reviews", b =>
                {
                    b.HasOne("Hoteldotnetserver.Entities.Properties", "Property")
                        .WithMany("Reviews")
                        .HasForeignKey("_propertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hoteldotnetserver.Entities.Users", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("_userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hoteldotnetserver.Entities.Amenities", b =>
                {
                    b.Navigation("PropertyAmenities");
                });

            modelBuilder.Entity("Hoteldotnetserver.Entities.Bookings", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Hoteldotnetserver.Entities.Properties", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("PropertyAmenities");

                    b.Navigation("PropertyImages");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Hoteldotnetserver.Entities.Users", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Properties");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
